name: Issues Workflow
on:
  issues:
    types: [opened, edited, closed]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - name: Print Issue Title and Body
      run: |
        echo "${{ github.event.issue.title }}"
        echo "${{ github.event.issue.body }}"
      
